// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransportRequest.proto

package cn.togeek.netty.message;

public final class Transport {
  private Transport() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code cn.togeek.netty.message.TransportType}
   */
  public enum TransportType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CHANNEL_INIT = 1;</code>
     */
    CHANNEL_INIT(0, 1),
    /**
     * <code>HEARTBEAT_REQ = 2;</code>
     */
    HEARTBEAT_REQ(1, 2),
    /**
     * <code>HEARTBEAT_RES = 3;</code>
     */
    HEARTBEAT_RES(2, 3),
    /**
     * <code>DDX_REQ = 4;</code>
     */
    DDX_REQ(3, 4),
    /**
     * <code>DDX_RES = 5;</code>
     */
    DDX_RES(4, 5),
    ;

    /**
     * <code>CHANNEL_INIT = 1;</code>
     */
    public static final int CHANNEL_INIT_VALUE = 1;
    /**
     * <code>HEARTBEAT_REQ = 2;</code>
     */
    public static final int HEARTBEAT_REQ_VALUE = 2;
    /**
     * <code>HEARTBEAT_RES = 3;</code>
     */
    public static final int HEARTBEAT_RES_VALUE = 3;
    /**
     * <code>DDX_REQ = 4;</code>
     */
    public static final int DDX_REQ_VALUE = 4;
    /**
     * <code>DDX_RES = 5;</code>
     */
    public static final int DDX_RES_VALUE = 5;


    public final int getNumber() { return value; }

    public static TransportType valueOf(int value) {
      switch (value) {
        case 1: return CHANNEL_INIT;
        case 2: return HEARTBEAT_REQ;
        case 3: return HEARTBEAT_RES;
        case 4: return DDX_REQ;
        case 5: return DDX_RES;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TransportType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TransportType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TransportType>() {
            public TransportType findValueByNumber(int number) {
              return TransportType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cn.togeek.netty.message.Transport.getDescriptor().getEnumTypes().get(0);
    }

    private static final TransportType[] VALUES = values();

    public static TransportType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TransportType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:cn.togeek.netty.message.TransportType)
  }

  public interface EntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.togeek.netty.message.Entity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string url = 1;</code>
     */
    boolean hasUrl();
    /**
     * <code>optional string url = 1;</code>
     */
    java.lang.String getUrl();
    /**
     * <code>optional string url = 1;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>optional string method = 2;</code>
     */
    boolean hasMethod();
    /**
     * <code>optional string method = 2;</code>
     */
    java.lang.String getMethod();
    /**
     * <code>optional string method = 2;</code>
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    /**
     * <code>optional string payload = 3;</code>
     */
    boolean hasPayload();
    /**
     * <code>optional string payload = 3;</code>
     */
    java.lang.String getPayload();
    /**
     * <code>optional string payload = 3;</code>
     */
    com.google.protobuf.ByteString
        getPayloadBytes();
  }
  /**
   * Protobuf type {@code cn.togeek.netty.message.Entity}
   */
  public static final class Entity extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:cn.togeek.netty.message.Entity)
      EntityOrBuilder {
    // Use Entity.newBuilder() to construct.
    private Entity(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Entity(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Entity defaultInstance;
    public static Entity getDefaultInstance() {
      return defaultInstance;
    }

    public Entity getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Entity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              url_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              method_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              payload_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.togeek.netty.message.Transport.internal_static_cn_togeek_netty_message_Entity_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.togeek.netty.message.Transport.internal_static_cn_togeek_netty_message_Entity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.togeek.netty.message.Transport.Entity.class, cn.togeek.netty.message.Transport.Entity.Builder.class);
    }

    public static com.google.protobuf.Parser<Entity> PARSER =
        new com.google.protobuf.AbstractParser<Entity>() {
      public Entity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Entity(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Entity> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int URL_FIELD_NUMBER = 1;
    private java.lang.Object url_;
    /**
     * <code>optional string url = 1;</code>
     */
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string url = 1;</code>
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          url_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string url = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_FIELD_NUMBER = 2;
    private java.lang.Object method_;
    /**
     * <code>optional string method = 2;</code>
     */
    public boolean hasMethod() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string method = 2;</code>
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          method_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string method = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYLOAD_FIELD_NUMBER = 3;
    private java.lang.Object payload_;
    /**
     * <code>optional string payload = 3;</code>
     */
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string payload = 3;</code>
     */
    public java.lang.String getPayload() {
      java.lang.Object ref = payload_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          payload_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string payload = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPayloadBytes() {
      java.lang.Object ref = payload_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payload_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      url_ = "";
      method_ = "";
      payload_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUrlBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMethodBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPayloadBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUrlBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMethodBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPayloadBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.togeek.netty.message.Transport.Entity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.togeek.netty.message.Transport.Entity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.togeek.netty.message.Transport.Entity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.togeek.netty.message.Transport.Entity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.togeek.netty.message.Transport.Entity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.togeek.netty.message.Transport.Entity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.togeek.netty.message.Transport.Entity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.togeek.netty.message.Transport.Entity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.togeek.netty.message.Transport.Entity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.togeek.netty.message.Transport.Entity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.togeek.netty.message.Transport.Entity prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.togeek.netty.message.Entity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.togeek.netty.message.Entity)
        cn.togeek.netty.message.Transport.EntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.togeek.netty.message.Transport.internal_static_cn_togeek_netty_message_Entity_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.togeek.netty.message.Transport.internal_static_cn_togeek_netty_message_Entity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.togeek.netty.message.Transport.Entity.class, cn.togeek.netty.message.Transport.Entity.Builder.class);
      }

      // Construct using cn.togeek.netty.message.Transport.Entity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        method_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        payload_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.togeek.netty.message.Transport.internal_static_cn_togeek_netty_message_Entity_descriptor;
      }

      public cn.togeek.netty.message.Transport.Entity getDefaultInstanceForType() {
        return cn.togeek.netty.message.Transport.Entity.getDefaultInstance();
      }

      public cn.togeek.netty.message.Transport.Entity build() {
        cn.togeek.netty.message.Transport.Entity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.togeek.netty.message.Transport.Entity buildPartial() {
        cn.togeek.netty.message.Transport.Entity result = new cn.togeek.netty.message.Transport.Entity(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.method_ = method_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.payload_ = payload_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.togeek.netty.message.Transport.Entity) {
          return mergeFrom((cn.togeek.netty.message.Transport.Entity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.togeek.netty.message.Transport.Entity other) {
        if (other == cn.togeek.netty.message.Transport.Entity.getDefaultInstance()) return this;
        if (other.hasUrl()) {
          bitField0_ |= 0x00000001;
          url_ = other.url_;
          onChanged();
        }
        if (other.hasMethod()) {
          bitField0_ |= 0x00000002;
          method_ = other.method_;
          onChanged();
        }
        if (other.hasPayload()) {
          bitField0_ |= 0x00000004;
          payload_ = other.payload_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.togeek.netty.message.Transport.Entity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.togeek.netty.message.Transport.Entity) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object url_ = "";
      /**
       * <code>optional string url = 1;</code>
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string url = 1;</code>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            url_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string url = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string url = 1;</code>
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string url = 1;</code>
       */
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000001);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string url = 1;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        url_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object method_ = "";
      /**
       * <code>optional string method = 2;</code>
       */
      public boolean hasMethod() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string method = 2;</code>
       */
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            method_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string method = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string method = 2;</code>
       */
      public Builder setMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string method = 2;</code>
       */
      public Builder clearMethod() {
        bitField0_ = (bitField0_ & ~0x00000002);
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <code>optional string method = 2;</code>
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        method_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object payload_ = "";
      /**
       * <code>optional string payload = 3;</code>
       */
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string payload = 3;</code>
       */
      public java.lang.String getPayload() {
        java.lang.Object ref = payload_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            payload_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string payload = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPayloadBytes() {
        java.lang.Object ref = payload_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          payload_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string payload = 3;</code>
       */
      public Builder setPayload(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string payload = 3;</code>
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000004);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      /**
       * <code>optional string payload = 3;</code>
       */
      public Builder setPayloadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        payload_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:cn.togeek.netty.message.Entity)
    }

    static {
      defaultInstance = new Entity(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:cn.togeek.netty.message.Entity)
  }

  public interface TransportorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.togeek.netty.message.Transportor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string transport_id = 1;</code>
     */
    boolean hasTransportId();
    /**
     * <code>optional string transport_id = 1;</code>
     */
    java.lang.String getTransportId();
    /**
     * <code>optional string transport_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getTransportIdBytes();

    /**
     * <code>optional .cn.togeek.netty.message.TransportType type = 2 [default = DDX_REQ];</code>
     */
    boolean hasType();
    /**
     * <code>optional .cn.togeek.netty.message.TransportType type = 2 [default = DDX_REQ];</code>
     */
    cn.togeek.netty.message.Transport.TransportType getType();

    /**
     * <code>optional .cn.togeek.netty.message.Entity entity = 3;</code>
     */
    boolean hasEntity();
    /**
     * <code>optional .cn.togeek.netty.message.Entity entity = 3;</code>
     */
    cn.togeek.netty.message.Transport.Entity getEntity();
    /**
     * <code>optional .cn.togeek.netty.message.Entity entity = 3;</code>
     */
    cn.togeek.netty.message.Transport.EntityOrBuilder getEntityOrBuilder();
  }
  /**
   * Protobuf type {@code cn.togeek.netty.message.Transportor}
   */
  public static final class Transportor extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:cn.togeek.netty.message.Transportor)
      TransportorOrBuilder {
    // Use Transportor.newBuilder() to construct.
    private Transportor(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Transportor(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Transportor defaultInstance;
    public static Transportor getDefaultInstance() {
      return defaultInstance;
    }

    public Transportor getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Transportor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              transportId_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              cn.togeek.netty.message.Transport.TransportType value = cn.togeek.netty.message.Transport.TransportType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
            case 26: {
              cn.togeek.netty.message.Transport.Entity.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = entity_.toBuilder();
              }
              entity_ = input.readMessage(cn.togeek.netty.message.Transport.Entity.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(entity_);
                entity_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.togeek.netty.message.Transport.internal_static_cn_togeek_netty_message_Transportor_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.togeek.netty.message.Transport.internal_static_cn_togeek_netty_message_Transportor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.togeek.netty.message.Transport.Transportor.class, cn.togeek.netty.message.Transport.Transportor.Builder.class);
    }

    public static com.google.protobuf.Parser<Transportor> PARSER =
        new com.google.protobuf.AbstractParser<Transportor>() {
      public Transportor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Transportor(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Transportor> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TRANSPORT_ID_FIELD_NUMBER = 1;
    private java.lang.Object transportId_;
    /**
     * <code>optional string transport_id = 1;</code>
     */
    public boolean hasTransportId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string transport_id = 1;</code>
     */
    public java.lang.String getTransportId() {
      java.lang.Object ref = transportId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          transportId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string transport_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTransportIdBytes() {
      java.lang.Object ref = transportId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transportId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private cn.togeek.netty.message.Transport.TransportType type_;
    /**
     * <code>optional .cn.togeek.netty.message.TransportType type = 2 [default = DDX_REQ];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .cn.togeek.netty.message.TransportType type = 2 [default = DDX_REQ];</code>
     */
    public cn.togeek.netty.message.Transport.TransportType getType() {
      return type_;
    }

    public static final int ENTITY_FIELD_NUMBER = 3;
    private cn.togeek.netty.message.Transport.Entity entity_;
    /**
     * <code>optional .cn.togeek.netty.message.Entity entity = 3;</code>
     */
    public boolean hasEntity() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .cn.togeek.netty.message.Entity entity = 3;</code>
     */
    public cn.togeek.netty.message.Transport.Entity getEntity() {
      return entity_;
    }
    /**
     * <code>optional .cn.togeek.netty.message.Entity entity = 3;</code>
     */
    public cn.togeek.netty.message.Transport.EntityOrBuilder getEntityOrBuilder() {
      return entity_;
    }

    private void initFields() {
      transportId_ = "";
      type_ = cn.togeek.netty.message.Transport.TransportType.DDX_REQ;
      entity_ = cn.togeek.netty.message.Transport.Entity.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTransportIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, entity_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTransportIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, entity_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.togeek.netty.message.Transport.Transportor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.togeek.netty.message.Transport.Transportor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.togeek.netty.message.Transport.Transportor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.togeek.netty.message.Transport.Transportor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.togeek.netty.message.Transport.Transportor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.togeek.netty.message.Transport.Transportor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.togeek.netty.message.Transport.Transportor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.togeek.netty.message.Transport.Transportor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.togeek.netty.message.Transport.Transportor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.togeek.netty.message.Transport.Transportor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.togeek.netty.message.Transport.Transportor prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.togeek.netty.message.Transportor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.togeek.netty.message.Transportor)
        cn.togeek.netty.message.Transport.TransportorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.togeek.netty.message.Transport.internal_static_cn_togeek_netty_message_Transportor_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.togeek.netty.message.Transport.internal_static_cn_togeek_netty_message_Transportor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.togeek.netty.message.Transport.Transportor.class, cn.togeek.netty.message.Transport.Transportor.Builder.class);
      }

      // Construct using cn.togeek.netty.message.Transport.Transportor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEntityFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        transportId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = cn.togeek.netty.message.Transport.TransportType.DDX_REQ;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (entityBuilder_ == null) {
          entity_ = cn.togeek.netty.message.Transport.Entity.getDefaultInstance();
        } else {
          entityBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.togeek.netty.message.Transport.internal_static_cn_togeek_netty_message_Transportor_descriptor;
      }

      public cn.togeek.netty.message.Transport.Transportor getDefaultInstanceForType() {
        return cn.togeek.netty.message.Transport.Transportor.getDefaultInstance();
      }

      public cn.togeek.netty.message.Transport.Transportor build() {
        cn.togeek.netty.message.Transport.Transportor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.togeek.netty.message.Transport.Transportor buildPartial() {
        cn.togeek.netty.message.Transport.Transportor result = new cn.togeek.netty.message.Transport.Transportor(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.transportId_ = transportId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (entityBuilder_ == null) {
          result.entity_ = entity_;
        } else {
          result.entity_ = entityBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.togeek.netty.message.Transport.Transportor) {
          return mergeFrom((cn.togeek.netty.message.Transport.Transportor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.togeek.netty.message.Transport.Transportor other) {
        if (other == cn.togeek.netty.message.Transport.Transportor.getDefaultInstance()) return this;
        if (other.hasTransportId()) {
          bitField0_ |= 0x00000001;
          transportId_ = other.transportId_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasEntity()) {
          mergeEntity(other.getEntity());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.togeek.netty.message.Transport.Transportor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.togeek.netty.message.Transport.Transportor) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object transportId_ = "";
      /**
       * <code>optional string transport_id = 1;</code>
       */
      public boolean hasTransportId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string transport_id = 1;</code>
       */
      public java.lang.String getTransportId() {
        java.lang.Object ref = transportId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            transportId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string transport_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTransportIdBytes() {
        java.lang.Object ref = transportId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transportId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string transport_id = 1;</code>
       */
      public Builder setTransportId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        transportId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string transport_id = 1;</code>
       */
      public Builder clearTransportId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        transportId_ = getDefaultInstance().getTransportId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string transport_id = 1;</code>
       */
      public Builder setTransportIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        transportId_ = value;
        onChanged();
        return this;
      }

      private cn.togeek.netty.message.Transport.TransportType type_ = cn.togeek.netty.message.Transport.TransportType.DDX_REQ;
      /**
       * <code>optional .cn.togeek.netty.message.TransportType type = 2 [default = DDX_REQ];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .cn.togeek.netty.message.TransportType type = 2 [default = DDX_REQ];</code>
       */
      public cn.togeek.netty.message.Transport.TransportType getType() {
        return type_;
      }
      /**
       * <code>optional .cn.togeek.netty.message.TransportType type = 2 [default = DDX_REQ];</code>
       */
      public Builder setType(cn.togeek.netty.message.Transport.TransportType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .cn.togeek.netty.message.TransportType type = 2 [default = DDX_REQ];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = cn.togeek.netty.message.Transport.TransportType.DDX_REQ;
        onChanged();
        return this;
      }

      private cn.togeek.netty.message.Transport.Entity entity_ = cn.togeek.netty.message.Transport.Entity.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          cn.togeek.netty.message.Transport.Entity, cn.togeek.netty.message.Transport.Entity.Builder, cn.togeek.netty.message.Transport.EntityOrBuilder> entityBuilder_;
      /**
       * <code>optional .cn.togeek.netty.message.Entity entity = 3;</code>
       */
      public boolean hasEntity() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .cn.togeek.netty.message.Entity entity = 3;</code>
       */
      public cn.togeek.netty.message.Transport.Entity getEntity() {
        if (entityBuilder_ == null) {
          return entity_;
        } else {
          return entityBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .cn.togeek.netty.message.Entity entity = 3;</code>
       */
      public Builder setEntity(cn.togeek.netty.message.Transport.Entity value) {
        if (entityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          entity_ = value;
          onChanged();
        } else {
          entityBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .cn.togeek.netty.message.Entity entity = 3;</code>
       */
      public Builder setEntity(
          cn.togeek.netty.message.Transport.Entity.Builder builderForValue) {
        if (entityBuilder_ == null) {
          entity_ = builderForValue.build();
          onChanged();
        } else {
          entityBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .cn.togeek.netty.message.Entity entity = 3;</code>
       */
      public Builder mergeEntity(cn.togeek.netty.message.Transport.Entity value) {
        if (entityBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              entity_ != cn.togeek.netty.message.Transport.Entity.getDefaultInstance()) {
            entity_ =
              cn.togeek.netty.message.Transport.Entity.newBuilder(entity_).mergeFrom(value).buildPartial();
          } else {
            entity_ = value;
          }
          onChanged();
        } else {
          entityBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .cn.togeek.netty.message.Entity entity = 3;</code>
       */
      public Builder clearEntity() {
        if (entityBuilder_ == null) {
          entity_ = cn.togeek.netty.message.Transport.Entity.getDefaultInstance();
          onChanged();
        } else {
          entityBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .cn.togeek.netty.message.Entity entity = 3;</code>
       */
      public cn.togeek.netty.message.Transport.Entity.Builder getEntityBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getEntityFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .cn.togeek.netty.message.Entity entity = 3;</code>
       */
      public cn.togeek.netty.message.Transport.EntityOrBuilder getEntityOrBuilder() {
        if (entityBuilder_ != null) {
          return entityBuilder_.getMessageOrBuilder();
        } else {
          return entity_;
        }
      }
      /**
       * <code>optional .cn.togeek.netty.message.Entity entity = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          cn.togeek.netty.message.Transport.Entity, cn.togeek.netty.message.Transport.Entity.Builder, cn.togeek.netty.message.Transport.EntityOrBuilder> 
          getEntityFieldBuilder() {
        if (entityBuilder_ == null) {
          entityBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              cn.togeek.netty.message.Transport.Entity, cn.togeek.netty.message.Transport.Entity.Builder, cn.togeek.netty.message.Transport.EntityOrBuilder>(
                  getEntity(),
                  getParentForChildren(),
                  isClean());
          entity_ = null;
        }
        return entityBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:cn.togeek.netty.message.Transportor)
    }

    static {
      defaultInstance = new Transportor(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:cn.togeek.netty.message.Transportor)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_togeek_netty_message_Entity_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cn_togeek_netty_message_Entity_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_togeek_netty_message_Transportor_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cn_togeek_netty_message_Transportor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026TransportRequest.proto\022\027cn.togeek.nett" +
      "y.message\"6\n\006Entity\022\013\n\003url\030\001 \001(\t\022\016\n\006meth" +
      "od\030\002 \001(\t\022\017\n\007payload\030\003 \001(\t\"\223\001\n\013Transporto" +
      "r\022\024\n\014transport_id\030\001 \001(\t\022=\n\004type\030\002 \001(\0162&." +
      "cn.togeek.netty.message.TransportType:\007D" +
      "DX_REQ\022/\n\006entity\030\003 \001(\0132\037.cn.togeek.netty" +
      ".message.Entity*a\n\rTransportType\022\020\n\014CHAN" +
      "NEL_INIT\020\001\022\021\n\rHEARTBEAT_REQ\020\002\022\021\n\rHEARTBE" +
      "AT_RES\020\003\022\013\n\007DDX_REQ\020\004\022\013\n\007DDX_RES\020\005B&\n\027cn" +
      ".togeek.netty.messageB\tTransportH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cn_togeek_netty_message_Entity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_togeek_netty_message_Entity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cn_togeek_netty_message_Entity_descriptor,
        new java.lang.String[] { "Url", "Method", "Payload", });
    internal_static_cn_togeek_netty_message_Transportor_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_togeek_netty_message_Transportor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cn_togeek_netty_message_Transportor_descriptor,
        new java.lang.String[] { "TransportId", "Type", "Entity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
